name: "@sandwich-ui/core Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/core-pull-request.yml"
      - "packages/core/**"

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks

    steps:
      - uses: actions/checkout@v7

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter @sandwich-ui/core

      - name: Check
        run: pnpm check --filter @sandwich-ui/core
