name: "@sandwich-ui/react Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/react-pull-request.yml"
      - "packages/react/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

  build:
    needs: setup
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter @sandwich-ui/react

  lint:
    needs: setup
    runs-on: ubuntu-latest
    name: Analyze

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Lint
        run: pnpm lint --filter @sandwich-ui/react
